### ISSUE TITLE
Mediawiki errors

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#128]
The SPA upgrades broke the mediawiki installatoin.
I have upgraded to latest mediawiki and wordpress on both staging and live servers, and installed php 5.6

On the staging server everything is peachy, apart from some CSS issues
https://staging.hoxtonowl.com/wiki/Main_Page

On the live server the page fails to load. Commenting out this part (menu bar) allows most of the content to load up:

```
                    <a href="<?php echo get_option('home'); ?>"><img id="logo" src="<?php echo get_bloginfo('template_directory');?>/images/logo.png" alt="Hoxton Owl"></a>
                    <ul id="primary-nav-items">
                        <?php wp_nav_menu( array( 'container_class' => 'main-nav', 'theme_location' => 'primary' ) ); ?>
                    </ul>
```

(https://github.com/pingdynasty/OwlServer/blob/master/web/mediawiki/skins/HoxtonOWL2014/HoxtonOWL2014.skin.php line 112)

See:
https://hoxtonowl.com/mediawiki/index.php/Main_Page

I've tried to enable PHP errors et c but not having any luck troubleshooting this error.

**Comment by pingdynasty** [comment]
It might have smth to do with the WPMW extension.
Loading this results in
```
Exception encountered, of type "InvalidArgumentException"
[be6d76b8cff5575140954cde] /mediawiki/index.php/Main_Page InvalidArgumentException from line 194 of /var/www/hoxtonowl.com/subdomains/www/httpdocs/mediawiki/includes/session/SessionManager.php: Invalid session ID
Backtrace:
#0 /var/www/hoxtonowl.com/subdomains/www/httpdocs/mediawiki/includes/session/SessionManager.php(126): MediaWiki\Session\SessionManager->getSessionById(string, boolean, WebRequest)
#1 /var/www/hoxtonowl.com/subdomains/www/httpdocs/mediawiki/includes/Setup.php(745): MediaWiki\Session\SessionManager::getGlobalSession()
#2 /var/www/hoxtonowl.com/subdomains/www/httpdocs/mediawiki/includes/WebStart.php(137): require_once(string)
#3 /var/www/hoxtonowl.com/subdomains/www/httpdocs/mediawiki/index.php(40): require(string)
#4 {main}
```

**Comment by pingdynasty** [comment]
The error comes from `mediawiki/includes/session/SessionManager.php`
Seems that mediawiki is expecting a 32 character ID but only receiving 24.
Changing to this works and allows the WPMW extension to load:
```
        /**
         * Validate a session ID
         * @param string $id
         * @return bool
         */
        public static function validateSessionId( $id ) {
                return is_string( $id ) && preg_match( '/^[a-zA-Z0-9_-]{24,}$/', $id );
        }
```
